@echo off
rem 명령어 복창 끔

rem ### 버전정보	:	v1.2.1_stable for All
rem ### 코드정보	:	https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=superyeoju&logNo=221747717398
rem ### updated by LJS 

rem chcp 65001>nul
rem 참고 https://otrodevym.tistory.com/entry/windows-10-cmd-%EC%9D%B8%EC%BD%94%EB%94%A9-utf-8-%EC%84%A4%EC%A0%95-%EB%B0%A9%EB%B2%95-949-65001-1

setLocal EnableDelayedExpansion
rem 참고 https://kkamagistory.tistory.com/881

rem 0 = 검정색 8 = 회색
rem 1 = 파랑색 9 = 연한 파랑색
rem 2 = 초록색 A = 연한 초록색
rem 3 = 옥색 B = 연한 옥색
rem 4 = 빨강색 C = 연한 빨강색
rem 5 = 자주색 D = 연한 자주색
rem 6 = 노랑색 E = 연한 노랑색
rem 7 = 흰색 F = 밝은 흰색
rem color 09
rem 첫째 자리는 배경, 둘째 자리는 글자색

rem mode con cols=60 lines=30
rem 콘솔창 크기 지정

rem ####################################

cd /d %~dp0
rem 현재 파일 위치 경로를 작업 위치로

title 현재 경로 : %cd%
:notice
rem echo 	## 업데이트 내역 ##
rem 		## 1.2.1 forAll용으로 전환
rem 		## 1.2.0 팀을 위한 그룹 폴더 생성기 릴리즈1
rem 		## 1.1.3 작은 변경
rem 		## 1.1.2 몇가지 코드 수정 및 최적화
rem 		## 1.1.1 ANSI코드로 변경(이전 버전은 글자 깨질 수 있음)
rem 		## 1.1.1 %를 분수로 변경
rem echo 	## 1.1.0 D그룹 완성 ##
rem echo 	## 1.0.3 C그룹 완성 ##
rem echo 	## 1.0.3 ※접두 대분류는 빼는 걸로 결론남. 분기 나눌 것 ##
rem echo 	## 1.0.2 B그룹 완성 ##
rem echo 	## 1.0.2 배치파일 작업 책임자님께 허락 맡음 ##
rem echo 	## 1.0.1 A그룹 완성 ##
rem echo.
rem echo 	프로그램을 실행하려면 아무 키나 누르세요
rem pause
rem goto ChoiceGroup

:ChoiceGroup
echo 	## 그룹폴더 자동생성기입니다 ##
echo 	## 그룹을 입력하세요 ##
echo 	예) B-1그룹 : b(대소문자 무관) 엔터 1 엔터
set /p group=Group: 

rem echo ## 그룹 번호를 입력하세요 ##
rem echo ## 예) B-1이면 1 입력
set /p groupNum=GroupNumber : 
goto confirm

:confirm
if %group% equ a set group=A
if %group% equ b set group=B
if %group% equ c set group=C
if %group% equ d set group=D

echo ## 선택한 그룹: %group%-%groupNum% ##
echo 실행하시겠습니까? 
rem set /p confirm= Y / N : 
choice /c 12 /m "	1.실행 	2.처음으로 돌아가기"
rem if /i %confirm% equ y goto gotoGroup
rem if /i %confirm% equ n cls&goto ChoiceGroup
if %errorlevel% equ 1 goto gotoGroup
if %errorlevel% equ 2 cls&goto ChoiceGroup

cls 
goto ChoiceGroup

:gotoGroup
rem @echo on
title %group%-%groupNum% 현재 경로 : %cd%
if /i %group% equ A goto A
if /i %group% equ B goto B
if /i %group% equ C goto C
if /i %group% equ D goto D
goto ChoiceGroup

:A
rem echo A
for /l %%i in (1,1,10) do (
if %groupNum% equ %%i goto A%%i
)
goto ChoiceGroup

:B
echo B
for /l %%i in (1,1,10) do (
if %groupNum% equ %%i goto B%%i
)
goto ChoiceGroup

:C
echo C
for /l %%i in (1,1,10) do (
if %groupNum% equ %%i goto C%%i
)
goto ChoiceGroup

:D
for /l %%i in (1,1,5) do (
if %groupNum% equ %%i goto D%%i
)
goto ChoiceGroup

:A1
cls
mkdir "비 소리"&echo 1/10...
mkdir "개 소리"&echo 2/10...
mkdir "기침 소리"&echo 3/10...
mkdir "가글하는 소리"&echo 4/10...
mkdir "물 마시는 소리"&echo 5/10...
mkdir "과자 먹는 소리"&echo 6/10...
mkdir "코 훌쩍거리는 소리"&echo 7/10...
mkdir "코 푸는 소리"&echo 8/10...
mkdir "껌 씹는 소리"&echo 9/10...
mkdir "땅콩 먹는 소리"&echo 10/10...

goto quit

:A2
cls
mkdir "바람 소리"&echo 1/10...
mkdir "침 뱉는 소리"&echo 2/10...
mkdir "웃음 소리"&echo 3/10...
mkdir "뽀뽀하는 소리"&echo 4/10...
mkdir "앓는 소리"&echo 5/10...
mkdir "기합넣는 소리"&echo 6/10...
mkdir "자전거 종소리"&echo 7/10...
mkdir "휴대폰 소리"&echo 8/10...
mkdir "노크하는 소리"&echo 9/10...
mkdir "종이 구기는 소리"&echo 10/10...

goto quit


:A3
cls
mkdir "귀뚜라미 소리"&echo 1/10...
mkdir "금속 부딪히는 소리"&echo 2/10...
mkdir "캔 찌그러지는 소리"&echo 3/10...
mkdir "도어락 소리"&echo 4/10...
mkdir "바코드 찍는 소리"&echo 5/10...
mkdir "필기 하는 소리"&echo 6/10...
mkdir "타자 치는 소리"&echo 7/10...
mkdir "테이프 소리"&echo 8/10...
mkdir "믹서기 가는 소리"&echo 8/10...
mkdir "연필깎이 소리"&echo 10/10...

goto quit


:A4
cls
mkdir "모기 소리"&echo 1/10...
mkdir "수세미질 소리"&echo 2/10...
mkdir "가스레인지 소리"&echo 3/10...
mkdir "빻는 소리"&echo 4/10...
mkdir "쌀 소리"&echo 5/10...
mkdir "복합기 소리"&echo 6/10...
mkdir "벨크로 소리"&echo 7/10...
mkdir "유리 문지르는 소리"&echo 8/10...
mkdir "피리 소리"&echo 9/10...
mkdir "멜로디언 소리"&echo 10/10...


goto quit



:A5
cls
mkdir "비둘기 소리"&echo 1/10...
mkdir "과일(야채)깎는 소리"&echo 2/10...
mkdir "팽이 치는 소리"&echo 3/10...
mkdir "열쇠 따는 소리"&echo 4/10...
mkdir "케이블타이 소리"&echo 5/10...
mkdir "코털정리기 소리"&echo 6/10...
mkdir "비데 소리"&echo 7/10...
mkdir "랩핑 소리"&echo 8/10...
mkdir "호두 까는 소리"&echo 9/10...
mkdir "레고 소리"&echo 10/10...

goto quit


:A6
cls
mkdir "얼음 먹는 소리"&echo 1/10...
mkdir "사탕 먹는 소리"&echo 2/10...
mkdir "야채 먹는 소리"&echo 3/10...
mkdir "사과 먹는 소리"&echo 4/10...
mkdir "수박 먹는 소리"&echo 5/10...
mkdir "바게트 먹는 소리"&echo 6/10...
mkdir "생라면 먹는 소리"&echo 7/10...
mkdir "배 먹는 소리"&echo 8/10...
mkdir "무 먹는 소리"&echo 9/10...
mkdir "시리얼 먹는 소리"&echo 10/10...

goto quit


:A7
cls
mkdir "새 소리"			 &echo 1/10...
mkdir "박수 소리"			 &echo 2/10...
mkdir "세수 하는 소리"		 &echo 3/10...
mkdir "따귀(찰싹거리는)소리"	 &echo 4/10...
mkdir "가래 끓는 소리"		 &echo 5/10...
mkdir "입 푸는 소리"		 &echo 6/10...
mkdir "호루라기 소리"		 &echo 7/10...
mkdir "PC 소리"			 &echo 8/10...
mkdir "비닐 구기는 소리"		 &echo 9/10...
mkdir "유리 부딪히는 소리"	 &echo 10/10...

goto quit


:A8
cls
mkdir "동물 빗질 소리"&echo 1/10...
mkdir "플라스틱 구기는 소리"&echo 2/10...
mkdir "스테이플러 소리"&echo 3/10...
mkdir "커피포트 끓는 소리"&echo 4/10...
mkdir "자동차 경적 소리"&echo 5/10...
mkdir "칼질하는 소리"&echo 6/10...
mkdir "마우스 클릭하는 소리"&echo 7/10...
mkdir "시계 소리"&echo 8/10...
mkdir "드라이기 소리"&echo 9/10...
mkdir "세탁기 소리"&echo 10/10...

goto quit


:A9
cls
mkdir "사료 먹는 소리"&echo 1/10...
mkdir "병 따는 소리"&echo 2/10...
mkdir "빗자루질 소리"&echo 3/10...
mkdir "전기채 소리"&echo 4/10...
mkdir "밥솥 소리"&echo 5/10...
mkdir "사포질 소리"&echo 6/10...
mkdir "은박지 소리"&echo 7/10...
mkdir "탄산음료 따르는 소리"&echo 8/10...
mkdir "캐스터네츠 소리"&echo 9/10...
mkdir "오토바이 시동 소리"&echo 10/10...
echo.

goto quit


:A10
cls
mkdir "휴대용 손풍기 소리"&echo 1/10...
mkdir "락카 소리"&echo 2/10...
mkdir "통조림 따는 소리"&echo 3/10...
mkdir "보글보글 끓는 소리"&echo 4/10...
mkdir "장기알 소리"&echo 5/10...
mkdir "보풀제거기 소리"&echo 6/10...
mkdir "제모기 소리"&echo 7/10...
mkdir "의자(책상)삐그덕 소리"&echo 8/10...
mkdir "뿅망치 소리"&echo 9/10...
mkdir "똑딱이 소리"&echo 10/10...

goto quit


:B1
cls
mkdir "고양이 소리"&echo 1/10...
mkdir "풀벌레 소리"&echo 2/10...
mkdir "벌 소리"&echo 3/10...
mkdir "매미 소리"&echo 4/10...
mkdir "까치 소리"&echo 5/10...
mkdir "나뭇잎 흔들리는 소리"&echo 6/10...
mkdir "비명 소리"&echo 7/10...
mkdir "걷는 소리"&echo 8/10...
mkdir "뛰는 소리"&echo 9/10...
mkdir "공 치는 소리"&echo 10/10...

goto quit


:B2
cls
mkdir "줄넘기 하는 소리"&echo 1/10...
mkdir "살 문지르는 소리"&echo 2/10...
mkdir "물거품 내는 소리"&echo 3/10...
mkdir "관절 꺾는 소리"&echo 4/10...
mkdir "참외 먹는 소리"&echo 5/10...
mkdir "복숭아 먹는 소리"&echo 6/10...
mkdir "건어물 씹는 소리"&echo 7/10...
mkdir "튀김 먹는 소리"&echo 8/10...
mkdir "비트박스 하는 소리"&echo 9/10...
mkdir "혀 튕기는 소리"&echo 10/10...

goto quit


:B3
cls
mkdir "초인종 소리"&echo 1/10...
mkdir "천 찢어지는 소리"&echo 2/10...
mkdir "의자(책상)끄는 소리"&echo 3/10...
mkdir "문 여닫는 소리"&echo 4/10...
mkdir "분무기 소리"&echo 5/10...
mkdir "전자레인지 소리"&echo 6/10...
mkdir "라이터 소리"&echo 7/10...
mkdir "캔 따는 소리"&echo 8/10...
mkdir "지퍼 소리"&echo 9/10...
mkdir "스티로폼 소리"&echo 10/10...

goto quit


:B4
cls
mkdir "천 긁는 소리"
echo 1/10...
mkdir "카메라 소리"
echo 2/10...
mkdir "태엽 감는 소리"
echo 3/10...
mkdir "커튼 소리"
echo 4/10...
mkdir "뽁뽁이 소리"
echo 5/10...
mkdir "화투 소리"
echo 6/10...
mkdir "다리미 소리"
echo 7/10...
mkdir "전동 드라이버 소리"
echo 8/10...
mkdir "종이 넘기는 소리"
echo 9/10...
mkdir "물 내리는 소리"
echo 10/10...

goto quit


:B5
cls
mkdir "물통 흔드는 소리"
echo 1/10...
mkdir "트라이앵글 소리"
echo 2/10...
mkdir "엘리베이터 소리"
echo 3/10...
mkdir "구슬치는 소리"
echo 4/10...
mkdir "칠판 긁는 소리"
echo 5/10...
mkdir "윷 던지는 소리"
echo 6/10...
mkdir "건조기 소리"
echo 7/10...
mkdir "지문인식기 소리"
echo 8/10...
mkdir "수타치는 소리"
echo 9/10...
mkdir "철 끄는 소리"
echo 10/10...

goto quit


:B6
cls
mkdir "닭 소리"
echo 1/10...
mkdir "돌 구르는 소리"
echo 2/10...
mkdir "물 떨어지는 소리"
echo 3/10...
mkdir "참새 소리"
echo 4/10...
mkdir "까마귀 소리"
echo 5/10...
mkdir "하품하는 소리"
echo 6/10...
mkdir "호로록 거리는 소리"
echo 7/10...
mkdir "밟는 소리"
echo 8/10...
mkdir "환호하는 소리"
echo 9/10...
mkdir "양치하는 소리"
echo 10/10...

goto quit


:B7
cls
mkdir "손빨래 하는 소리"
echo 1/10...
mkdir "젤리 먹는 소리"
echo 2/10...
mkdir "팝콘먹는 소리"
echo 3/10...
mkdir "발성연습 소리"
echo 4/10...
mkdir "옥수수 먹는 소리"
echo 5/10...
mkdir "치아 부딪히는 소리"
echo 6/10...
mkdir "귤 먹는 소리"
echo 7/10...
mkdir "야유하는 소리"
echo 8/10...
mkdir "쉿 소리"
echo 9/10...
mkdir "배추 먹는 소리"
echo 10/10...

goto quit


:B8
cls
mkdir "돌 부딪히는 소리"
echo 1/10...
mkdir "플라스틱 부딪히는 소리"
echo 2/10...
mkdir "에어프라이어 소리"
echo 3/10...
mkdir "바퀴 굴러가는 소리"
echo 4/10...
mkdir "장난감 소리"
echo 5/10...
mkdir "칼 가는 소리"
echo 6/10...
mkdir "동전 떨어지는 소리"
echo 7/10...
mkdir "빨대 소리"
echo 8/10...
mkdir "커피머신 소리"
echo 9/10...
mkdir "풍선 소리"
echo 10/10...

goto quit


:B9
cls
mkdir "프린터 소리"
echo 1/10...
mkdir "자석 부딪히는 소리"
echo 2/10...
mkdir "계란 소리"
echo 3/10...
mkdir "바둑알 소리"
echo 4/10...
mkdir "강판 가는 소리"
echo 5/10...
mkdir "공기청정기 소리"
echo 6/10...
mkdir "금고 소리"
echo 7/10...
mkdir "솔질 소리"
echo 8/10...
mkdir "자동문 소리"
echo 9/10...
mkdir "공구함 소리"
echo 10/10...

goto quit


:B10
cls
mkdir "탬버린 소리"
echo 1/10...
mkdir "실로폰 소리"
echo 2/10...
mkdir "나무 깎는 소리"
echo 3/10...
mkdir "딱지치는 소리"
echo 4/10...
mkdir "가습기 소리"
echo 5/10...
mkdir "토스트기 소리"
echo 6/10...
mkdir "뻥튀기 기계 소리"
echo 7/10...
mkdir "샴페인 따는 소리"
echo 8/10...
mkdir "키질하는 소리"
echo 9/10...
mkdir "당구공 소리"
echo 10/10...

goto quit

rem ## C그룹 ##

:C1
cls
mkdir "물 흐르는 소리"
echo 1/10...
mkdir "소 소리"
echo 2/10...
mkdir "오리 소리"
echo 3/10...
mkdir "트림 소리"
echo 4/10...
mkdir "헛기침하는 소리"
echo 5/10...
mkdir "울음 소리"
echo 6/10...
mkdir "긁는 소리"
echo 7/10...
mkdir "이 가는 소리"
echo 8/10...
mkdir "옹알이 하는 소리"
echo 9/10...
mkdir "아카펠라 소리"
echo 10/10...

goto quit


:C2
cls
mkdir "손가락 튕기는 소리"
echo 1/10...
mkdir "딸꾹질 소리"
echo 2/10...
mkdir "꼬로록 거리는 소리"
echo 3/10...
mkdir "요들 소리"
echo 4/10...
mkdir "유리 깨지는 소리"
echo 5/10...
mkdir "세단기 소리"
echo 6/10...
mkdir "다듬이질 소리"
echo 7/10...
mkdir "토치 소리"
echo 8/10...
mkdir "라디오 지지직 소리"
echo 9/10...
mkdir "목탁 소리"
echo 10/10...

goto quit


:C3
cls
mkdir "망치 소리"
echo 1/10...
mkdir "톱류"
echo 2/10...
mkdir "튀기는 소리"
echo 3/10...
mkdir "계량기 소리"
echo 4/10...
mkdir "스위치 소리"
echo 5/10...
mkdir "기타 튜닝 소리"
echo 6/10...
mkdir "바이올린 튜닝 소리"
echo 7/10...
mkdir "가야금 튜닝 소리"
echo 8/10...
mkdir "우쿠렐레 튜닝 소리"
echo 9/10...
mkdir "색소폰 튜닝 소리"
echo 10/10...

goto quit


:C4
cls
mkdir "불 타는 소리"
echo 1/10...
mkdir "면도하는 소리"
echo 2/10...
mkdir "조이스틱 소리"
echo 3/10...
mkdir "징 튜닝 소리"
echo 4/10...
mkdir "트랙터 시동 소리"
echo 5/10...
mkdir "이앙기 시동 소리"
echo 6/10...
mkdir "과일나무 터는 소리"
echo 7/10...
mkdir "칫솔살균기 소리"
echo 8/10...
mkdir "착즙기 소리"
echo 9/10...
mkdir "반죽기 소리"
echo 10/10...

goto quit


:C5
cls
mkdir "펄럭이는 소리"
echo 1/10...
mkdir "블라인드 소리"
echo 2/10...
mkdir "급정거(급출발) 하는 소리"
echo 3/10...
mkdir "부채 소리"
echo 4/10...
mkdir "구강세정기 소리"
echo 5/10...
mkdir "호미질 하는 소리"
echo 6/10...
mkdir "제빙기 소리"
echo 7/10...
mkdir "제면기 소리"
echo 8/10...
mkdir "무전기 소리"
echo 9/10...
mkdir "주유하는 소리"
echo 10/10...

goto quit


:C6
cls
mkdir "돼지 소리"
echo 1/10...
mkdir "말 소리"
echo 2/10...
mkdir "양 소리"
echo 3/10...
mkdir "한숨쉬는 소리"
echo 4/10...
mkdir "헐떡이는 소리"
echo 5/10...
mkdir "웅성거리는 소리"
echo 6/10...
mkdir "헛 구역질 하는 소리"
echo 7/10...
mkdir "기지개 켜는 소리"
echo 8/10...
mkdir "콧노래 소리"
echo 9/10...
mkdir "카드 단말기 소리"
echo 10/10...

goto quit


:C7
cls
mkdir "휘파람 소리"
echo 1/10...
mkdir "재채기 하는 소리"
echo 2/10...
mkdir "손방귀 소리"
echo 3/10...
mkdir "자동차 경보음"
echo 4/10...
mkdir "방앗간 기계"
echo 5/10...
mkdir "계수기 소리"
echo 6/10...
mkdir "휘젓는 소리"
echo 7/10...
mkdir "체인 돌아가는 소리"
echo 8/10...
mkdir "굽는 소리"
echo 9/10...
mkdir "풍경 소리"
echo 10/10...

goto quit


:C8
cls
mkdir "삽류"
echo 1/10...
mkdir "펀치류"
echo 2/10...
mkdir "볶는 소리"
echo 3/10...
mkdir "바리깡 소리"
echo 4/10...
mkdir "식기세척기 소리"
echo 5/10...
mkdir "드럼 소리"
echo 6/10...
mkdir "피아노 튜닝 소리"
echo 7/10...
mkdir "거문고 튜닝 소리"
echo 8/10...
mkdir "단소 튜닝 소리"
echo 9/10...
mkdir "장구 튜닝 소리"
echo 10/10...

goto quit


:C9
cls
mkdir "0_뿌리는 소리"
echo 1/10...
mkdir "0_재봉틀 소리"
echo 2/10...
mkdir "0_꽹과리 튜닝 소리"
echo 3/10...
mkdir "0_경운기 시동 소리"
echo 4/10...
mkdir "0_콤바인 시동 소리"
echo 5/10...
mkdir "0_탈곡기 시동 소리"
echo 6/10...
mkdir "0_북 소리"
echo 7/10...
mkdir "0_포장기 소리"
echo 8/10...
mkdir "0_팬히터 소리"
echo 9/10...
mkdir "0_뽑기 기계 소리"
echo 10/10...

goto quit


:C10
cls
mkdir "안마기 소리"
echo 1/10...
mkdir "첼로 소리"
echo 2/10...
mkdir "맷돌 소리"
echo 3/10...
mkdir "큐브 만지는 소리"
echo 4/10...
mkdir "낫질 하는 소리"
echo 5/10...
mkdir "오르골 소리"
echo 6/10...
mkdir "동전분류기 소리"
echo 7/10...
mkdir "도리깨질 소리"
echo 8/10...
mkdir "쿨러거치대 소리"
echo 9/10...
mkdir "샌드백 타격 소리"
echo 10/10...

goto quit

rem ## D그룹 끝 ##

:D1
cls
mkdir "파도 소리"
echo 1/10...
mkdir "모닥불 소리"
echo 2/10...
mkdir "꼬르륵 소리"
echo 3/10...
mkdir "젖병 빠는 소리"
echo 4/10...
mkdir "학교 알람소리"
echo 5/10...

goto quit


:D2
cls
mkdir "잠꼬대 하는 소리"
echo 1/10...
mkdir "화재경보"
echo 2/10...
mkdir "비상경보"
echo 3/10...
mkdir "진자운동 모빌 소리"
echo 4/10...
mkdir "안경세척기 소리"
echo 5/10...

goto quit


:D3
cls
mkdir "코 고는 소리"
echo 1/6...
mkdir "종소리"
echo 2/6...
mkdir "가스누출 경보소리"
echo 3/6...
mkdir "나무 갈라지는 소리"
echo 4/6...
mkdir "전기 소리"
echo 5/6...
mkdir "스파크 튀는 소리"
echo 6/6...

goto quit


:D4
cls
mkdir "줄 가는 소리"
echo 1/5...
mkdir "스프링쿨러 소리"
echo 2/5...
mkdir "오븐 소리"
echo 3/5...
mkdir "메트로놈 소리"
echo 4/5...
mkdir "눈썹정리기 소리"
echo 5/5...

goto quit


:D5
cls
mkdir "응급경보"
echo 1/5...
mkdir "도난경보"
echo 2/5...
mkdir "방역하는 소리"
echo 3/5...
mkdir "탈수기 소리"
echo 4/5...
mkdir "떡매치는 소리"
echo 5/5...

goto quit

:quit
echo %group%-%groupNum% 그룹 폴더 생성 완료
pause
quit


rem cls
rem mkdir "0_"
rem echo 1/10...
rem mkdir "0_"
rem echo 2/10...
rem mkdir "0_"
rem echo 3/10...
rem mkdir "0_"
rem echo 4/10...
rem mkdir "0_"
rem echo 5/10...
rem mkdir "0_"
rem echo 6/10...
rem mkdir "0_"
rem echo 7/10...
rem mkdir "0_"
rem echo 8/10...
rem mkdir "0_"
rem echo 9/10...
rem mkdir "0_"
rem 
rem goto quit

rem &echo 1/10...
rem &echo 2/10...
rem &echo 3/10...
rem &echo 4/10...
rem &echo 5/10...
rem &echo 6/10...
rem &echo 7/10...
rem &echo 8/10...
rem &echo 9/10...
rem &echo 10/10...
